title: "CV Aldric KOUMASSOU"
logo: C:/Users/user/Desktop/DOCS/School/Rapport de stage KOUMASSOU/1/Mon_CV/img_cv.jpg
description: "Ceci est un exemple de site GitHub Pages."
show_downloads: true
theme: jekyll-theme-minimal
lang: fr
